# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.14.1-25-gec0d803
_src_path: gh:tsvikas/python-template
format_tool: ruff
get_package_version_from_vcs: true
github_user: tsvikas
has_cli: false
jupyter_files: forbid
license: MIT
package_description: MCP server for amazing marvin.
package_name: marvin_mcp_server
project_name: marvin-mcp-server
python_min: 13
user_email: tsvikas@gmail.com
user_name: Tsvika Shapira
year: 2025
